# Generated by Django 5.2.8 on 2025-12-11 20:57

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_instructor_approval_pending_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookprovider',
            name='provider_id',
            field=models.CharField(default=core.models.generate_provider_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='textbook',
            name='textbook_id',
            field=models.CharField(default=core.models.generate_textbook_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
    ]
