# Generated by Django 5.2.8 on 2025-12-12 17:41

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_bookprovider_provider_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(default=core.models.generate_course_id, editable=False, max_length=10, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='section',
            name='section_id',
            field=models.CharField(default=core.models.generate_section_id, editable=False, max_length=20, primary_key=True, serialize=False),
        ),
    ]
